FROM centos
RUN ["echo","image building!!!"]
#docker run mcj010/docker_run ls , CMD skip
#CMD ["echo","container starting..."]
#ENTRYPOINT ["echo","container starting..."]
ENTRYPOINT ["ps"]
#docker run mcj010/docker_run -aux 这样就会忽略CMD而使用-aux
CMD ["-ef"]