#用DC 3.3解析
version: '3.3'
#父節點
services: 
  db:
  #解釋dockerfile
    build: ./bsbdj-db/
    #容器down 了自動重啟
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: ./bsbdj-app/
    depends_on: 
      - db
    ports:
      - "80:80"
    restart: always